jtoy/awesome-tensorflow

README.md

Added Keras to list of libraries

added Keras

---

README.md

Train a deep learning net with OpenStreetMap features and satellite imagery.

add my project using TensorFlow

---

README.md

See https://github.com/tjhunter/tensorframes

Added TensorFrames project

---

README.md

add an author of 'First Contact with TensorFlow' and add a new book 'Deel Learning with Python'

add an author and a book

---

README.md

TensorFlow implementation of DeepMind's 'Human-Level Control through Deep Reinforcement Learning' with OpenAI Gym by Devsisters.com
Devsisters makes online and mobile games in Korea.

add a TensorFlow implementation

---

README.md

Hi, I made a project recently and it is presented as a tutorial. 
You might add it to your list, as tutorials on Recurrent Neural Networks and LSTMs are rarer. 
Thanks!

Added a tutorial on RNNs

---

README.md

https://bleedingedgepress.com/tensor-flow-for-machine-intelligence/

Added book from Bleeding Edge Press

---

README.md

https://github.com/domluna/memn2n

TF Implementation of End-To-End Memory Networks

---

README.md

Implementation of "A Neural Conversational Model"

Add tf chatbot

---

README.md

Tensorflow implementation of Character-Aware Neural Language Models.

Add Character-Aware Neural Language Models.

---

README.md

With training part and actual support for real-time running on mobile devices

Add new project: YOLO: Real-time object detection

---

README.md

Added a new book under Books and a new video under Videos

Added a new book and video

---

README.md

This is a upgraded version of previous TensorFlow project for "show, attend and tell".

Adding Show, Attend and Tell Model

---

README.md

To increase a bit of understandability

Minor change in README

---

README.md

I suggest adding my book to the list of TensorFlow books.  It covers everything from the Machine Learning basics using Scikit-Learn, to advanced Deep Learning topics (eg. Xavier/He initialization, batch normalization, data/model parallelism, RMS Prop, Adam optimization, the latest CNNs, RNNs, various Autoencoder architectures, Deep Q learning, and much more) using TensorFlow.  The code examples and exercise solutions are open sourced at https://github.com/ageron/handson-ml/.

Add Hands-on ML book

---

README.md

Add WaveNet model from [ibab/tensorflow-wavenet](https://github.com/ibab/tensorflow-wavenet).

Add a TensorFlow implementation of DeepMind's WaveNet paper.

---

README.md

Rename 'Tensorflow' to 'TensorFlow' in README.md file

---

README.md

Added the Mnemonic Descent Method, from CVPR '16.

Added Mnemonic Descent Method

---

README.md

Useful guide to RNNs in TF. Reasonably recent;

WildML RNN guide blog link

---

README.md

Added blog post on Using TensorBoard to Visualize Image Classification Retraining in TensorFlow.

Added blog post on TensorBoard

---

README.md

[Tensorflow and deep learning - without at PhD](https://www.youtube.com/watch?v=vq2nnJ4g6N0) -  by Martin Görner

add a new tutorial video by Martin Görner

---

README.md

I added a repo containing a real-time object detection on Android using the YOLO network powered by TensorFlow.

Updated list with object detection android app: android-yolo

---

README.md

implementation of Facebook's Unsupervised Cross-Domain Image Generation

Add Domain Transfer Network

---

README.md

Corrected formatting and readability

Formatting Errors

---

README.md

https://github.com/omimo/awesome-tensorflow

Adding Android Tutorial

---

README.md

- "Predict time series" is a new tutorial of mine about using sequence to sequence (seq2seq) RNN architectures.
- "Sonnet" is Google DeepMind's new library built on top of TensorFlow.
Both added at the end of their respective category

Added "Predict time series" tutorial and "Sonnet", DeepMind's new library

---

README.md

Adding a CNN visualization tool designed in tensorflow.

Adding new entry under Projects- a CNN visualization tool.

---

README.md

Add tensorpack, a Neural Network Toolbox on TensorFlow focusing on training speed and on large datasets.

Add tensorpack

---

README.md

The TensorFlow team changed the name for the project.

Update "SK Flow" -> "tf.contrib.learn"

---

README.md

Added link to a Tensorflow implementation of VGAN by Vondrick et al.

Updated README with VGAN implementation tensorflow

---

README.md

pull request from this issue #102 - https://github.com/jtoy/awesome-tensorflow/issues/102 
Further remarks: I even found unofficial videos based on the course slides (so I included a link to the playlist)

Add Stanford Course - CS20 SI: TensorFlow for DeepLearning Research

---

README.md

Fix markdown link typos

---

README.md

Update TensorFlow twitter link

Use official TensorFlow twitter

---

README.md

Link: https://github.com/vahidk/EffectiveTensorflow

Added EffectiveTensorflow to tutorials.

---

README.md

See Nickel et al, https://arxiv.org/pdf/1510.04935.pdf

Add Link to HolE implementation/Tensordboard embedding viz

---

README.md

Update with 2 new libraries

---

README.md

I added a tensorflow project template in the projects section, it's a simple and well-designed template for any tensorflow projects, that contains the basic functionalities you need in every tensorflow project.

Adding tensorflow project template repo in the "Projects" section

---

README.md

A suggested additional project. Facebook's fastText library is extremely popular for text classification. This implementation is inspired by that.

Added tensor flow_fasttext

---

README.md

Add video: Image recognition in Go using TensorFlow

---

README.md

Hi, thank you for this collection. 
I would like to add TensorLayer to the library list, and some selected examples.

Add TensorLayer and Selected Examples

---

README.md

https://github.com/kubeflow/kubeflow

Added Kubeflow

---

README.md

Thank you for this collection. I would like to add TensorNets to the list.

Add TensorNets

---

README.md

https://github.com/mlachmish/MusicGenreClassification

Update Readme with MusicGenreClassification Project

---

README.md

TensorIO is a cross-platform library for using TensorFlow lite models on mobile devices. Support for iOS and React Native with Android support forthcoming.

Added TensorIO to the ReadMe

---

README.md

Guild AI doesn't really fit into the existing categories so I took the liberty of creating a new "Tools/Utilities" section.

Link to Guild AI

---

README.md

PR:
* Adds [StellarGraph](https://github.com/stellargraph/stellargraph) - Machine Learning on Graphs, a Python library for machine learning on graph-structured (network-structured) data.

add StellarGraph library

---

README.md

[Link to it here](https://github.com/juniorxsound/TF-Unet)

Add TF-Unet project

---

README.md

Hey @jtoy 
While checking the models I've found some broken links.
Cheers!

Removing some broken links

---

README.md

- Add links of Model Maker
- Fix a format bug in the page

Add Model Maker to Models/Projects

---

README.md

Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,

Added TensorFlow 2.0 in Action

---

README.md

Added the tfp library along with a book on Bayesian programming using it
- [Tensorflow-Probability](https://www.tensorflow.org/probability)
- [Probabilistic Programming and Bayesian Methods for Hackers](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers)

Tensorflow-probability

---

README.md

Hey @jtoy,
just fixing the link for gluon2keras. It seems to have moved maybe?
Cheers,
Peter

Fixing gluon2keras link

---

README.md

Hi, 
I have updated the library name and one liner of nebullvm. I am a maintainer of this library.
Best, Emile

Update library name and one liner

---

README.md

Txeo is a lightweight and intuitive C++ wrapper for TensorFlow, designed to simplify TensorFlow C++ development while preserving high performance and flexibility. Built entirely with Modern C++, Txeo allows developers to use TensorFlow with the ease of a high-level API, eliminating the complexity of its low-level C++ interface.

Add Txeo: A modern C++ wrapper for TensorFlow
